# Generated by Django 4.2 on 2023-04-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('year', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('english', 'english'), ('tamil', 'tamil'), ('telungu', 'telungu'), ('malayalm', 'malayalm')], default='malayalm', max_length=200)),
                ('runtime', models.FloatField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.CharField(max_length=200, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genres')),
            ],
        ),
    ]
