# Generated by Django 4.2 on 2023-04-18 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_remove_movies_genre_alter_movies_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(choices=[('telungu', 'telungu'), ('malayalm', 'malayalm'), ('tamil', 'tamil'), ('english', 'english')], default='malayalm', max_length=200),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.PositiveBigIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
